repos:
  # Ruff: linter + formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1        # pin to a release tag
    hooks:
      - id: ruff-check
        args: ["--fix", "--exit-non-zero-on-fix"]  # auto-fix & fail so you re-commit reviewed fixes
        types_or: [python, pyi]                    # skip ipynb by default
      - id: ruff-format
        types_or: [python, pyi]

  # Lightweight hygiene hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
